#!/bin/bash -x

lambda_function_name={{raw-name}}

aws lambda delete-function \
	--function-name "$lambda_function_name"

aws iam delete-role-policy \
	--role-name "$lambda_function_name-role" \
	--policy-name "$lambda_function_name-policy"

aws iam delete-role
	--role-name "$lambda_function_name-role" \

exit 0
